In [2]:
import pandas as pd

df_games = pd.read_csv('/home/user1/project/fifa_prediction/results.csv')

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [9]:
print(df_games.shape)
df_games.head()

(49477, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [4]:
df_games.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [5]:
historical_matches = df_games[df_games['home_score'].notna()].copy()
wc2026_fixtures = df_games[df_games['home_score'].isna()].copy()

In [6]:
print(historical_matches.shape)
historical_matches.head()

(49425, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [7]:
print(wc2026_fixtures.shape)
wc2026_fixtures.head()

(52, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49425,2026-06-17,Portugal,DR Congo,NaN,NaN,FIFA World Cup,Houston,United States,True
49426,2026-06-17,Uzbekistan,Colombia,NaN,NaN,FIFA World Cup,Mexico City,Mexico,True
49427,2026-06-17,England,Croatia,NaN,NaN,FIFA World Cup,Arlington,United States,True
49428,2026-06-17,Ghana,Panama,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49429,2026-06-18,Czech Republic,South Africa,NaN,NaN,FIFA World Cup,Atlanta,United States,True

In [11]:
historical_matches.to_csv('/home/user1/project/fifa_prediction/historical_matches.csv', index=False)
wc2026_fixtures.to_csv('/home/user1/project/fifa_prediction/wc2026_fixtures.csv', index=False)

print(f"Historical matches: {len(historical_matches)}")
print(f"WC2026 fixtures: {len(wc2026_fixtures)}")

Historical matches: 49425
WC2026 fixtures: 52